Numpy 
Pandas
Matplot lib
Scikir Learn (Sklearn)

Iris Dataset Accuracy

# NUMPY

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [10]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(b)

numpy.ndarray

In [12]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
b.dtype

dtype('int32')

### Matrix Creation

np.Zeros

In [16]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr1=np.zeros((5,), dtype=int)

In [19]:
arr1

array([0, 0, 0, 0, 0])

In [20]:
arr1.dtype

dtype('int32')

In [22]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.ones

In [25]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [26]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
print(1+np.ones((3,3)))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### np.eye

In [29]:
arr=np.eye((2),dtype=int)
print(arr)

[[1 0]
 [0 1]]


In [32]:
arr=np.eye((3),dtype=int)
print(arr)
print(arr.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)


### np.diag

In [33]:
arr=np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [34]:
arr=np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Generate Random Float

In [35]:
r=np.random.rand(2,2)
r

array([[0.03115921, 0.45020093],
       [0.6446595 , 0.81893778]])

In [37]:
r=np.random.randn(2,2)
r

array([[ 2.22569299,  1.21287684],
       [-0.36866678, -0.65823312]])

## Generate Random Array

In [40]:
rand_arr=np.random.randint(10,size=(5))
rand_arr

array([4, 7, 3, 0, 6])

In [41]:
rand_arr=np.random.randint(10,size=(2,3))
rand_arr

array([[6, 4, 5],
       [0, 2, 8]])

In [42]:
rand_arr=np.random.rand(5)
rand_arr

array([0.8538188 , 0.26207529, 0.67701289, 0.09243581, 0.96023623])

In [43]:
min=10
max=20
rand_arr=min+((max-min)*np.random.rand())
print(rand_arr)


17.12070730640704


## Reshaping

In [44]:
arr=np.random.randint(1,50,10)
arr

array([28, 18, 15, 19,  2, 25, 13, 42, 35, 35])

In [45]:
arr.shape

(10,)

In [46]:
arr=arr.reshape(2,5)
arr


array([[28, 18, 15, 19,  2],
       [25, 13, 42, 35, 35]])

In [47]:
arr.shape

(2, 5)

## revel()

In [50]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

### arange